### ISSUE TITLE
Multisite Subdomains - Documentation / Proper Way To Set Up

### ISSUE THREAD

**Issue by ScroLLDan** [wpengine/hgv#259]
I can't get my multisite subdomains to work.

I set up a .yml file with `multisite: domain`

and the resulting site `example.local` is a multisite that works just fine on its own.

But when I add a sub domain like `sub.example.local` to that multisite via the WordPress backend, I get an `ERR_NAME_NOT_RESOLVED` when I visit that url.

I tried adding `192.168.150.20 sub.example.local` to my hosts file, but that just makes it show the hgv documentation when I visit the url.

I tried adding `sub.example.local` to my .yml file but that just makes another WordPress install at `sub.example.local` that's not hooked up to my main multisite `example.local`.

I'm not sure what the proper way to get subdomains working is, and the existing documentation is somewhat sparse. Something to do with nginx maybe?

**Comment by markkelnar** [comment]
@ScroLLDan That sounds interested.  I'd like to know more to try and recreate.  Adding 'sub.example.local' to the hgv_data/config/sites/ file shouldn't create a new WP.  The following vagrant up and vagrant provision will then add that domain to your /etc/hosts and creates the needed Nginx mapping for the domains in the stack.

Can you provide your YAML file?  Here of in a github gist.
And I'm curious to see part of your Nginx config for the WP.  Can you provide snippet of /etc/nginx/conf.d/www-foo.conf where foo matches the name of your config.  The line I'm looking for is the server_name line in the server block.

**Comment by ScroLLDan** [comment]
You're right it's not creating an entirely new site/folder. It does appear to be a sub site on the multisite. However, something's not quite right. 

My `sub.example.local` site isn't listed in the Sites tab that you find on individual sites. It also doesn't appear in the Network Admin sites dropdown. Also no matter what themes I enable or disable beyond the first or second for the `sub.example.local` site nothing changes on its Appearance -> Themes page.

My sub site is however listed on the Network Admin Sites tab where I originally added it from.

Here's my `hydra.yml` file in `hgv_data/config/sites/`:

```
# DO NOT EDIT: Default WP install and domains for HGV. Instead, copy to a new file under hgv_data/config/sites/.
---
wp:
  enviro: hydra
  multisite: domain
  hhvm_domains:
    - hydra.local
    - dan.hydra.local
  php_domains:
    - hydra-php.local
    - dan.hydra-php.local
```

So you can see here my actual domain names. Here's what happens on each:

* `hydra.local`: working multisite
* `dan.hydra.local`: not being listed in most places on multisite, enabling and disabling themes for it doesn't work
* `hydra-php.local`: redirects to `hydra.local` where it simply tells me registrations have been disabled
* `dan.hydra-php.local`: redirects to `hydra.local` where it simply tells me registrations have been disabled

Also of note: When I removed `php_domains:` and all its domains from my .yml file for testing, vagrant failed to provision saying `php_domains:` doesn't exist. Not sure if php is required by design, bug, or something on my system.

`hydra.conf` server name:
`server_name     hydra.local dan.hydra.local hydra-php.local dan.hydra-php.local;`

**Comment by ScroLLDan** [comment]
I thought the issue might be in my .yml file where I used two different domain names (`hydra.local` and `hydra-php.local`), but I changed it all be on the `hydra.local` domain and I still got the same issue. See below:

```
# DO NOT EDIT: Default WP install and domains for HGV. Instead, copy to a new file under hgv_data/config/sites/.
---
wp:
  enviro: hydra
  multisite: domain
  hhvm_domains:
    - hydra.local
    - dan.hydra.local
  php_domains:
    - php.hydra.local
    - danphp.hydra.local
```

**However, I discovered something new.**

Earlier I said enabling and disabling themes for sites from Network Admin was not doing anything. It appears that it will work, but I have to run the `vagrant reload` command each time after enabling or disabling a theme.
