### ISSUE TITLE
Multiple enviros in one hgv install

### ISSUE THREAD

**Issue by morganmccol** [wpengine/hgv#323]
This previous issue mentions having one hgv install with multiple sites by including a file located in hgv/hgv_data/config/sites/foo.yml:
https://github.com/wpengine/hgv/issues/44

But how should this file look? When I try something like:
```
wp:
    enviro: hhvm
    multisite: domain
    hhvm_domains:
        - hhvm.hgv.test
        - stage1.hhvm.hgv.test
        - stage2.hhvm.hgv.test
        - stage3.hhvm.hgv.test
    php_domains:
        - php.hgv.test
wp:
    enviro: foo
    multisite: directory
    hhvm_domains:
        - foo.test
    php_domains:
        - php.foo.test
```

The first wp enviro (hhvm) is ignored in favor of the second (foo). Foo works with no issues while hhvm leads to a redirect. The file creates a db for both enviros and they both have a folder in hgv_data/config/sites. Removing the second block from the file and provisioning allows hhvm to be accessed again with no issue.

What is the best way to set up the file to access both enviros in one install while keeping their data separate?

**Comment by andrew40** [comment]
Have you tried it with setting them both as domains or directory installs. I'm wondering if there are some shared resources that interferes with two types of multisite installation?

**Comment by morganmccol** [comment]
Hmm, I think I figured it out. Setting each site up as a separate .yml file and seems to be working. Using the example from my first post, I now have the following:

**hhvm.yml**
```
wp:
    enviro: hhvm
    multisite: domain
    hhvm_domains:
        - hhvm.hgv.test
        - stage1.hhvm.hgv.test
        - stage2.hhvm.hgv.test
        - stage3.hhvm.hgv.test
    php_domains:
        - php.hgv.test
```
**foo.yml**
```
wp:
    enviro: foo
    multisite: directory
    hhvm_domains:
        - foo.test
    php_domains:
        - php.foo.test
```

This allows me to have both sites running at the same time under one install.
