### ISSUE TITLE
Importing mysql.sql during provisioning

### ISSUE THREAD

**Issue by auginator** [wpengine/hgv#352]
I am just getting started with hgv, and I like the project a lot – despite being relatively new to vagrant setups this complex. 

I was able to set up my own site as per the docs with a `.yml` file
```
# mysite.dev
---
wp:
  enviro: mysite
  hhvm_domains:
    - mysite.dev
  php_domains:
    - php.mysite.dev
```
Should adding this line import the specified mysql dump during the provisioning sequence?
```
  mysql_import:
    - 'hgv_data/sites/mysite.dev/wp-content/mysql.sql'
```
I found that the `wp.mysql_import` parameter read in `/provisioning/wordpress.yml`, so I was hoping that might be the case!
